version: '2'
services:

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: investmentdb

  consul:
    image: gliderlabs/consul-server:latest
    command: -advertise=${MYHOST} -server -bootstrap
    container_name: consul
    hostname: ${MYHOST}
    ports:
      - 8500:8500

  registrator:
    image: gliderlabs/registrator:latest
    command: -ip ${MYHOST} consul://${MYHOST}:8500
    container_name: registrator
    hostname: ${MYHOST}
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  fund-service:
    image: zs_server/fund-service
    links:
      - mariadb:mariadb
    ports:
      - 6565
      - 10010
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mariadb

