version: '2'
services:

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: investmentdb

  discovery-service:
    build: discovery-service
    ports:
      - 10100:10100
    environment:
      SPRING_PROFILES_ACTIVE: docker

  kafka:
    image: spotify/kafka
    container_name: kafka
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      ADVERTISED_HOST: 127.0.0.1
      ADVERTISED_PORT: 9092

  edge-service:
    build: edge-service
    links:
      - fund-service:fund-service
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
  
  fund-service:
    build: fund-service
    command: /bin/bash -c "wait-for-it -t 0 mariadb:3306 && java -jar /app/fund-service-latest.jar"
    links:
      - mariadb:mariadb
    ports:
      - 10010:10010
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mariadb

  inventory-service:
    build: inventory-service
    links:
      - fund-service:fund-service
    ports:
      - 10011:10011
    environment:
      SPRING_PROFILES_ACTIVE: docker
 
  invest-service:
    build: invest-service
    links:
      - fund-service:fund-service
    ports:
      - 10012:10012
    environment:
      SPRING_PROFILES_ACTIVE: docker

  trade-service:
    build: trade-service
    links:
      - fund-service:fund-service
    ports:
      - 10013:10013
    environment:
      SPRING_PROFILES_ACTIVE: docker
