server:
  port: 10010

spring:
  profiles: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://192.168.99.100:3306/TEST?useSSL=true
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
---

server:
  port: 10010

spring:
  profiles: docker
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://192.168.99.100:3306/TEST?useSSL=true
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect