server:
  port: 8080

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    fund-service:
      path: /fund-service/**
      url: http://localhost:10010/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
---

spring:
  profiles: docker

server:
  port: 8080

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    fund-service:
      path: /fund-service/**
      url: http://fund-service:10010/
