app:
  version: "%%VERSION%%"
  
server:
  port: 8088

zuul:
  ignoredServices: "*"
  routes:
    fund-service:
      path: /fund-service/**
      url: http://120.77.178.46:10010/
    inventory-service:
      path: /inventory-service/**
      url: http://120.77.178.46:10011/

eureka:
  instance:
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5

---

spring:
  profiles: dev
  kafka:
    consumer:
      group-id: "test"
    bootstrap-servers: 120.77.178.46:9092
      


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://120.77.178.46:10100/eureka/

---

spring:
  profiles: prod


eureka:
  client:
    serviceUrl:
      defaultZone: http://discoery-service:10100/eureka/